from __future__ import annotations

from config import (
    CHUNK_ARTIFACTS_DIR,
    COLLECTION_NAME,
    EMBED_MODEL_NAME,
    RERANK_MODEL_NAME,
    VECTOR_PERSIST_DIR,
)

DEFAULT_ARTIFACTS_DIR = CHUNK_ARTIFACTS_DIR
DEFAULT_PERSIST_DIR = VECTOR_PERSIST_DIR
DEFAULT_COLLECTION = COLLECTION_NAME
DEFAULT_EMBED_MODEL = EMBED_MODEL_NAME
DEFAULT_RERANK_MODEL = RERANK_MODEL_NAME
DEFAULT_INITIAL_K = 24
DEFAULT_FINAL_K = 5
DEFAULT_DEVICE = "cuda"
EXPECTED_MURSIT_DIM = 1024
DEFAULT_SEARCH_TYPE = "hybrid"
DEFAULT_RERANK_POOL_K = 16

